# Generated by Django 3.1.6 on 2021-02-19 23:39

import browserApp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file3', models.FileField(blank=True, null=True, upload_to='')),
                ('file4', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='test', max_length=200)),
                ('user_grouping', models.CharField(default='irods', max_length=200)),
                ('pipeline', models.CharField(default='irods', max_length=500)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('Metadata_PDF', models.FileField(default=None, upload_to=browserApp.models.UploadedConfigPath)),
                ('Metadata_CellCount', models.FileField(default=None, upload_to=browserApp.models.UploadedConfigPath)),
                ('Metadata_CSV', models.FileField(default=None, upload_to=browserApp.models.UploadedConfigPath)),
                ('Deconvolution_File', models.FileField(default=None, null=True, upload_to=browserApp.models.UploadedConfigPath)),
                ('QC_metrics_JPGs', models.FileField(default=None, null=True, upload_to=browserApp.models.UploadedConfigPath)),
                ('QC_metrics_PDFs1', models.FileField(default=None, null=True, upload_to=browserApp.models.UploadedConfigPath)),
                ('QC_metrics_PDFs2', models.FileField(default=None, null=True, upload_to=browserApp.models.UploadedConfigPath)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
