# Generated by Django 3.1.6 on 2021-02-20 01:25

import browserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browserApp', '0002_auto_20210219_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='Deconvolution_File',
            field=models.FileField(blank=True, default=None, null=True, upload_to=browserApp.models.UploadedConfigPath),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='QC_metrics_JPGs',
            field=models.FileField(blank=True, default=None, null=True, upload_to=browserApp.models.UploadedConfigPath),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='QC_metrics_PDFs1',
            field=models.FileField(blank=True, default=None, null=True, upload_to=browserApp.models.UploadedConfigPath),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='QC_metrics_PDFs2',
            field=models.FileField(blank=True, default=None, null=True, upload_to=browserApp.models.UploadedConfigPath),
        ),
    ]
