# Generated by Django 3.1.6 on 2021-02-20 01:38

import browserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browserApp', '0003_auto_20210220_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='Metadata_PDF',
            field=models.FileField(default=None, null=True, upload_to=browserApp.models.UploadedConfigPath),
        ),
    ]
