import React, { Component, Fragment } from 'react'
import { Card, Box } from '@material-ui/core';
import StarBorder from '@material-ui/icons/StarBorder';
import DeleteIcon from '@material-ui/icons/Delete';
import Grid from '@material-ui/core/Grid';
import MoreHorizIcon from '@material-ui/icons/MoreHoriz';
import InfoIcon from '@material-ui/icons/Info';
import Logo from '../../../media_files/excel.svg';
import GetAppIcon from '@material-ui/icons/GetApp';
import { Document, Page } from 'react-pdf';
import { pdfjs } from 'react-pdf';
export class NestedList_CardDisplay extends Component {

    render() {
        const all_files = this.props.all_files
        return (
            <Grid justify="center" id="bottom-row" container spacing={4}>

                {Object.keys(all_files).map(file => {
                    if (all_files[file] !== null) {
                        if (file.includes("CSV")) {
                            return (
                                <Grid item xs={6} sm={3}>
                                    <h3>{file}<a data-tooltip={"Metadata CSV contains the statistics of raw data generated by sequencing and stored on the irods."}><InfoIcon /></a></h3>

                                    <Card variant="outlined" className={'PDF box'} style={{ "width": 220, height: 260, backgroundColor: "yellowgreen", display: 'flex', justifyContent: 'center' }}>
                                        <img width="170px" height="auto" src={Logo} alt="Logo" />
                                    </Card>
                                    <div><a href={all_files[file]}><GetAppIcon /> Download</a></div>
                                </Grid>
                            )
                        } else {
                            return (
                                <Grid item xs={6} sm={3}>
                                    <h3>{file}<a title={"Here we have used the Metadata PDF file to quickly visualise the most important statistics of the files to be used in the subsequent pipeline."}><InfoIcon /></a></h3>
                                    <a href={all_files[file]}><Card variant="outlined" className={'PDF box'} style={{ "width": 220, height: 260, padding: 5 }}>
                                        <Document file={all_files[file]}>
                                            <Page pageNumber={1} width={210} height={210} />
                                        </Document>
                                    </Card>
                                    </a>
                                    <div><a href={all_files[file]} download><GetAppIcon /> Download</a></div>
                                </Grid>
                            )
                        }

                    } else {
                        return <Fragment />
                    }

                })}

            </Grid>
        )
    }
}

export default NestedList_CardDisplay
