import React, { Component } from 'react'
import PipePic from '../../../media_files/flowchart.png';

export class Descriptions extends Component {

    render() {

        return (
            <div className="box">
                <img style={{width:'100%'}} src={PipePic}/>
                <div className={'paragraph_desc'}>
                    <h1 className={'title_description'} id="Fech pipeline">Fech pipeline </h1>
                    <p>
                        Fech pipeline pulls the Cellranger data of experiments according to list of IDs from lustre to irods. Subsequently a multiple metadata metrics are generated by default which include estimated cell counts, sequencing performance and other. This metadata can be retrieved ddirectly from our scRNA website per run.asellus vitae turpis purus. Nulla fringilla elit nulla, at vulputate erat gravida a. Aenean sit amet enim quis lacus porta auctor. Vivamus varius vehicula eleifend. Aliquam eu purus in justo ornare bibendum vel a libero. Mauris in elementum diam. Ut ut quam ultricies, elementum arcu vitae, malesuada quam. Mauris eget aliquam sapien. Suspendisse rhoncus tristique enim, sit amet faucibus augue fringilla at.

                </p>
                </div>
                <div className={'paragraph_desc'}>
                    <h1 className={'title_description'} id="Fech">Cellbender</h1>
                    <p>
                        Cellbender description to follow
                    </p>
                </div>
                <div className={'paragraph_desc'}>
                    <h1 className={'title_description'} id="Deconvolution">Deconvolution</h1>
                    <p>
                        For deconvolution CellSnp and Vireo are used to split the multiplexed donors. The output generates a plots per pool representing donors and shows the number of cells per donor after deconvolution.
                </p>
                </div>
                <div className={'paragraph_desc'}>
                    <h1 className={'title_description'} id="QC metrics">QC Metrics</h1>
                    <p>

                        This QC pipeline, developed almost exclusively by Leland Taylor and Monika Krzak, is the third piece in a trio of pipelines designed to work sequentially in order to ingest (continuous) batches of Cellranger data generated at Sanger (cellranger runs are placed by Sequencing into Irods) for the Cardinal project.</p>
                    <p>
                        <p>
                            This QC pipeline runs on the Sanger LSF farm, on a “batch” of (deconvoluted) single Cell data, which it merges, normalizes, QCs, annotates and clusters in a series of Nextflow tasks, producing numerous plots and output files along the way.
                            The input “batch” must be a set of scRNA data for multiple samples/donors, i.e. a list of individual deconvoluted donors scRNA data (deconvoluted from cellranger experiments(s) by the HGI Vireo deconvolution pipeline).</p>
                    </p>
                </div>
                <div className={'paragraph_desc'}>
                    <h1 className={'title_description'} id="Clustering">Clustering</h1>
                    <p>
                        Clustering pipeline description to go in here

                </p>
                </div>

            </div>

        )
    }
}

export default Descriptions
