import React, { Component } from 'react'

export class visualise_file_snaphots extends Component {
    render() {
        return (
            <div>
                
                    {/* here the pdfs and metadat is visualised */}
                    <div id={experiment.timestamp} style={{ display: "none" }}>
                      <Grid justify="center" id="bottom-row" container spacing={4}>
                        
                        <Grid item xs={6} sm={3}>
                          <h3>Metadata CSV <a data-tooltip={"Metadata CSV contains the statistics of raw data generated by sequencing and stored on the irods."}><InfoIcon/></a></h3>
                          
                          <Card variant="outlined" className={'PDF box'} style={{ "width": 220, height: 260, backgroundColor:"yellowgreen",display:'flex', justifyContent:'center' }}>
                          <img width="170px" height="auto"  src={Logo} alt="Logo" />
                          </Card>
                          <div><a onClick={() => alert("Download")}><GetAppIcon/> Download</a></div>
                        </Grid>


                        <Grid item xs={6} sm={3}>
                          <h3>Metadata PDF <a title={"Here we have used the Metadata PDF file to quickly visualise the most important statistics of the files to be used in the subsequent pipeline."}><InfoIcon/></a></h3>
                          <a href={experiment.Metadata_PDF}><Card variant="outlined" className={'PDF box'} style={{ "width": 220, height: 260, padding: 5 }}>
                            <Document file={experiment.Metadata_PDF}>
                              <Page pageNumber={1} width={210} height={210} />
                            </Document>
                          </Card>
                          </a>
                          <div><a onClick={() => alert("Download")}><GetAppIcon/> Download</a></div>
                        </Grid>


                        <Grid item xs={6} sm={3}>
                          <h3>Deconvolution PDFs <InfoIcon/></h3>
                          <Card variant="outlined" className={'PDF box'} style={{ "width": 220, height: 260 }}>
                            <Document file={experiment.Metadata_CSV}>
                              <Page pageNumber={1} width={210} height={210} />
                            </Document>
                          </Card>
                          <div><a onClick={() => alert("Download")}><GetAppIcon/> Download</a></div>
                        </Grid>
                        
                      </Grid>
                    </div> 
            </div>
        )
    }
}

export default visualise_file_snaphots
